name: C++ CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        build-type: [ Release, Debug ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build
        run: |
          cmake --build build --parallel

      - name: Test
        run: |
          cd build
          ctest --output-on-failure
