name: C++ CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        build-type: [ Release, Debug ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      # Install Ninja on Ubuntu
      - name: Install Ninja (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
        shell: bash

      # Install Ninja on macOS
      - name: Install Ninja (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install ninja
        shell: bash

      # Install Ninja on Windows
      - name: Install Ninja (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install ninja -y
        shell: powershell

      # Configure (single-config generator + build-type)
      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      # Build
      - name: Build
        run: cmake --build build --parallel

      # Test
      - name: Test
        run: ctest --test-dir build --output-on-failure
